rapid7/icon-integrations-validators

- .gitignore
- icon_validator/rules/plugin_validators/description_validator.py
fixed some grammar issues mike found in the depreciation validator
> Grammar fixs for depreciation validator

- README.md
- icon_validator/rules/__init__.py
- icon_validator/rules/workflow_validators/workflow_icon_filename_validator.py
- setup.py
- unit_test/test_validate.py
- unit_test/workflow_examples/icon_filename_tests/Automated Indicator Enrichment.icon
- unit_test/workflow_examples/icon_filename_tests/workflow.spec.yaml
Add validator that checks to ensure that the .icon filename dose not contain spaces
unit test with good data
unit test with bad data
> add icon filename validator

- README.md
- icon_validator/rules/__init__.py
- icon_validator/rules/workflow_validators/workflow_description_validator.py
- setup.py
- unit_test/test_validate.py
- unit_test/workflow_examples/description_tests/workflow_blank_description.spec.yaml
- unit_test/workflow_examples/description_tests/workflow_lower_case.spec.yaml
- unit_test/workflow_examples/description_tests/workflow_no_description.spec.yaml
- unit_test/workflow_examples/description_tests/workflow_no_period.spec.yaml
- unit_test/workflow_examples/description_tests/workflow_whitespace.spec.yaml
Add a description validator
[*] Running Integration Validators...
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowProfanityValidator
[*] Workflow successfully validated!
----
[*] Total time elapsed: 12.349ms
Ran 1 test …
> Description validator

- README.md
- icon_validator/rules/plugin_validators/title_validator.py
- setup.py
- unit_test/plugin_examples/plugin_number_title/plugin.spec.yaml
- unit_test/test_validate_plugin.py
- unit_test/test_validate_workflow.py
This PR fixes
* Numbers in titles would give lower case warning
* If the last word in the title was a special connector word (to, the, or, etc...) it should be capped
Testing: 
Added unit test. The test passed as expected.
> Title Validation Fixes

- README.md
- setup.py
Fix broken import
```
⇒  icon-validate --version
[*] insightconnect-integrations-validators 2.17.1
mrinehart@BOS-MBP-4466:~icon-plugins/cef|cef_amendments
⇒  icon-validate .
[*] Validating plugin at .
[*] Running Integration Validators...
[*] Executing validator HelpValidator
[*] Executing validator ChangelogValidator
[*] Executing validator RequiredKeysValidator
[*] Executing validator UseCaseValidator
[*] Executing validator SpecPropertiesValidator
[*] Executing validator SpecVersionValidator
[*] Executing validator FilesValidator
[*] Executing validator TagValidator
[*] Executing validator DescriptionValidator
[*] Executing validator TitleValidator
[*] Executing validator VendorValidator
[*] Executing validator DefaultValueValidator
[*] Executing validator IconValidator
[*] Executing …
```
> Fix imports

- README.md
- icon_validator/rules/__init__.py
- icon_validator/rules/workflow_validators/workflow_icon_validator.py
- setup.py
- unit_test/test_validate_workflow.py
- unit_test/workflow_examples/icon_file_tests/Automated_Indicator_Enrichment.icon
- unit_test/workflow_examples/icon_file_tests/workflow.spec_bad_icon_file.yaml
Add validator to check that the .icon file is properly formatted
Unit testing in CI
> Add .icon file validator

- README.md
- icon_validator/rules/__init__.py
- icon_validator/rules/plugin_validators/dockerfile_parent_validator.py
- icon_validator/rules/plugin_validators/runtime_validator.py
- setup.py
- Added new runtime validator for confirming usage of `insightconnect-plugin-runtime` in `setup.py`
- New runtime validator for checking usage of `insightconnect-plugin-runtime` vs `komand` imports
- New runtime validator for checking usage of caching in plugin actions
> SOAR-131 - Implement validators for runtime consistency

- README.md
- icon_validator/rules/plugin_validators/help_input_output_validator.py
- setup.py
- unit_test/plugin_examples/good_plugin/help.md
- unit_test/plugin_examples/good_plugin/komand_base64/actions/decode/action.py
- unit_test/plugin_examples/good_plugin/komand_base64/actions/encode/action.py
- unit_test/plugin_examples/good_plugin/plugin.spec.yaml
- unit_test/test_validate_plugin.py
Update HelpInputOutputValidator to validate on new Example inputs
Unit testing with new example keys in yaml and updated help. tested both with keys and for inputs missing a key in yaml.
> Update HelpInputOutputValidator to validate on new Example inputs

- icon_validator/rules/workflow_validators/workflow_title_validator.py
- unit_test/test_validate_workflow.py
- unit_test/workflow_examples/title_tests/numeric_in_title.yaml
This PR fixes the issue where the title validator thinks numeric values are lowercased
> Fix issue where "365 is lower case"

- README.md
- setup.py
This is a version bump for a previous PR. 
See: 
https://github.com/rapid7/icon-integrations-validators/commit/95741d4a00fd202d57a8a0f119e23f0f84812f3e
NA - docs change
> bumped version

- setup.py
Fixes version number in setup.py
> Fix version number for release

- README.md
- icon_validator/rules/plugin_validators/help_input_output_validator.py
- setup.py
- unit_test/plugin_examples/bad_plugin_array_in_help/help.md
- unit_test/plugin_examples/bad_plugin_array_in_help/plugin.spec.yaml
- unit_test/plugin_examples/good_plugin/help.md
- unit_test/plugin_examples/good_plugin/plugin.spec.yaml
- unit_test/test_validate_plugin.py
Update array syntax in HelpInputOutputValidator
There was added unit test.
> [SOAR-1302] update array syntax in HelpInputOutputValidator

- README.md
- icon_validator/rules/plugin_validators/version_validator.py
- setup.py
- unit_test/plugin_examples/version_validator/plugin.spec.yaml
- unit_test/plugin_examples/version_validator/plugin.spec_bad.yaml
- unit_test/test_validate_plugin.py
VersionValidator to identify a missing version bump
There was added unit test.
> [SOAR-1101] identify missing version bump

- README.md
- icon_validator/rules/plugin_validators/version_pin_validator.py
- setup.py
- unit_test/plugin_examples/version_pin_validator/plugin.spec.yaml
- unit_test/test_validate_plugin.py
Add Version Pin Validator
There was added unit test.
> Add Version Pin Validator

- README.md
- icon_validator/rules/plugin_validators/description_validator.py
- icon_validator/rules/plugin_validators/version_pin_validator.py
- setup.py
- unit_test/plugin_examples/bad_plugin_no_description/help.md
- unit_test/plugin_examples/bad_plugin_no_description/plugin.spec.yaml
- unit_test/test_validate_plugin.py
Update DescriptionValidator to print list of missing description field and Update VersionPinValidator to not fail when git is in requirements
There are Unit Tests
> Update DescriptionValidator to print list of missing description field and Update VersionPinValidator to not fail when git is in requirements

- icon_validator/rules/plugin_validators/version_validator.py
Fixes a typo in the version validator error message
> Swap vendor for version to fix typo

- .gitignore
- requirements.txt
- setup.py
Updates PyYAML and icon-plugin-spec-tooling versions
All unit tests pass
> Update dependencies to use latest PyYAML and plugin spec tool

- README.md
- icon_validator/rules/__init__.py
- icon_validator/rules/plugin_validators/encoding_validator.py
- icon_validator/rules/plugin_validators/help_example_validator.py
- icon_validator/rules/plugin_validators/unapproved_keywords_validator.py
- setup.py
- unit_test/plugin_examples/bad_plugin_help_example_wrong_json/help.md
- unit_test/plugin_examples/bad_plugin_help_example_wrong_json/plugin.spec.yaml
- unit_test/plugin_examples/bad_plugin_help_example_wrong_spaces/help.md
- unit_test/plugin_examples/bad_plugin_help_example_wrong_spaces/plugin.spec.yaml
- unit_test/plugin_examples/encoding_tests/plugin_bad_encoding.spec.yaml
- unit_test/plugin_examples/good_plugin_with_task/.CHECKSUM
- unit_test/plugin_examples/good_plugin_with_task/Makefile
- unit_test/plugin_examples/good_plugin_with_task/help.md
- unit_test/plugin_examples/version_validator/plugin.spec_bad.yaml
- unit_test/test_validate_plugin.py
Add HelpExampleVadalitor to  identify invalid JSON examples
Improve EncodingValidator to print all bad characters in one time
Tickets: MC-56 and MC-381
Unit test
> Add HelpExampleValidator and improve EncodingValidator

- README.md
- icon_validator/rules/__init__.py
- icon_validator/rules/workflow_validators/workflow_python_script_use_validator.py
- icon_validator/workflow/marshal.py
- icon_validator/workflow/model.py
- requirements.txt
- setup.py
- unit_test/test_validate_workflow.py
- unit_test/workflow_examples/python_plugin_used/Automated_Indicator_Enrichment.icon
- unit_test/workflow_examples/python_plugin_used/workflow.spec.yaml
Detects usage of the Python 3 Script plugin and warns of its use, giving the step name its used in.
```
[*] Running Integration Validators...
[*] Executing validator WorkflowPythonScriptUseValidator
[*] Workflow failed validation! The following validation errors occurred:
Validator "WorkflowPythonScriptUseValidator" failed! 
Cause: Python Plugin use found in these steps
[*] Step Name - Python script used to take over the world
[*] Step Name - Second attempt at trying to take over the world with a python script
Please review these steps carefully before use
```
> Python Script Plugin validator

- setup.py
This PR is a minor version bump in the setup.py file that was not updated in the previous SOAR-4712 supported versions validator PR.
JIRA: https://issues.corp.rapid7.com/browse/SOAR-4712
No functional changes.
> SOAR-4712: Version bump for supported versions validator

- README.md
- icon_validator/rules/workflow_validators/workflow_screenshot_validator.py
- setup.py
- unit_test/test_validate_workflow.py
- unit_test/workflow_examples/screenshot_tests/workflow_bad_title_start_with_dot.spec.yaml
- unit_test/workflow_examples/screenshot_tests/workflow_brackets_in_title.spec.yaml
Ticket MC-659
Add in WorkflowScreenshotValidator check parenthesis in screenshot title
Unit tests
> Add in WorkflowScreenshotValidator check parenthesis in screenshot title

- README.md
> added changelog entry

- README.md
- icon_validator/rules/plugin_validators/version_bump_validator.py
- setup.py
- PROPERLY fixed the validator by returning "None" all the way up the chain until we return from the validator. Previously the return took us out of one function call but not all of them, causing other problems. 
- 
> ACTUALLY fixed version Increment Validator

- README.md
- icon_validator/rules/plugin_validators/help_input_output_validator.py
- icon_validator/rules/plugin_validators/help_validator.py
- setup.py
- unit_test/plugin_examples/good_plugin/help.md
- unit_test/plugin_examples/good_plugin/plugin.spec.yaml
- unit_test/plugin_examples/good_plugin_with_task/.CHECKSUM
- unit_test/plugin_examples/good_plugin_with_task/help.md
- unit_test/plugin_examples/good_plugin_with_task/plugin.spec.yaml
Updating the validators for help.md to match the needs of plugin spec v3
Required:
Input examples
Output examples
Title (across the board)
Description (definitely components and inputs, not outputs)
Links (at least a vendor link)
Version History
Key features
Non-Required:
Help section (per component)
Troubleshooting (per component)
Requirements
> Soar-8241: Help.md Validator Update

- README.md
- icon_validator/rules/plugin_validators/version_validator.py
- setup.py
- unit_test/plugin_examples/version_validator/plugin.spec_bad.yaml
- unit_test/plugin_examples/version_validator/plugin.spec_ten.yaml
- unit_test/test_validate_plugin.py
- JIRA: https://issues.corp.rapid7.com/browse/SOAR-10008
- Fix version validator regex to match semantic version strings `>=1` with a `0` in the major version number, such as `10.0.0`.
> SOAR-10008: Patch version validator regex

- README.md
- icon_validator/rules/workflow_validators/workflow_title_validator.py
- setup.py
-  Fixed issue with WorkflowTitleValidator where it would not accept hyphens in titles or names
> [SOAR-13822] WorkflowTitleValidator Hyphen Fix

- README.md
- requirements.txt
- setup.py
- Update `GitGypthon` to version 3.1.32
https://issues.corp.rapid7.com/browse/SOAR-15380
> Gitpython version bump

- README.md
- icon_validator/rules/plugin_validators/confidential_validator.py
- setup.py
- unit_test/test_validate_plugin/test_validate_plugin.py
Update the email validator to show warning if the email did not match the example.
https://issues.corp.rapid7.com/browse/SOAR-15334
> [SOAR15334]- Updated email validator to show a warning if the example did not match

- README.md
- icon_validator/rules/plugin_validators/dockerfile_parent_validator.py
- icon_validator/rules/plugin_validators/runtime_validator.py
- requirements.txt
- setup.py
- unit_test/plugin_examples/good_plugin_with_task/Dockerfile
Bump validator to ensure that we validate against the new SDK image. 
- Make sure no validation errors raised against the new SDK image.
- Include dependabot PR: https://github.com/rapid7/icon-integrations-validators/pull/170
TODO:
Once PR is merged and new release of validator exists will need to update the following to pull these changes:
- https://github.com/rapid7/icon-integrations-ci
- https://github.com/rapid7/insight-plugin
> SOAR-16020: validate new SDK image

- README.md
- icon_validator/rules/plugin_validators/help_input_output_validator.py
- setup.py
- Update help_input_output_validator code to specify an error around the headers when we get the List Index out of range error.
> [SOAR-15905]- Handle List Index out of range error

- README.md
- requirements.txt
- setup.py
> Update PyYaml to 601

- README.md
- icon_validator/rules/plugin_validators/help_input_output_validator.py
- setup.py
- unit_test/plugin_examples/good_datetime_example/help.md
- unit_test/plugin_examples/good_plugin/help.md
- unit_test/plugin_examples/good_plugin_with_task/help.md
- Added code to catch when single quotes are used in list input values. These are then converted to double quotes so the validators pass.
- Unit tests failed after this due to some help.md's still using single quotes. Updated those values to avoid failing tests.
> SOAR-16333 - Fix help.md replacing quotes

- README.md
- icon_validator/rules/plugin_validators/output_validator.py
- setup.py
- unit_test/plugin_examples/good_plugin/example_venv/lib/python3.9/site-packages/schema.py
- unit_test/test_validate_plugin/test_validate_plugin.py
- Fix issue where `schema.py` files from the venv folder were being validated
> [PLGN-359] Output Validator - Fix issue where `schema.py` files from the venv folder were being validated

- README.md
- icon_validator/rules/plugin_validators/docker_validator.py
- Update the DockerValidator to use `insight-plugin` messages and to output the actual error message when validation fails.
> [SOAR-16531] DockerValidator - Output error
